; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter "dbg" --filter "^vector.body" --filter "^loop" --version 6
; RUN: opt -p loop-vectorize -force-vector-width=4 -force-vector-interleave=1 -S < %s | FileCheck %s

; The debug attached to the urem instruction should remain after
; being folded to `and i64 %iv, 15`
define void @urem_fold(ptr %dst, ptr %src, i64 %n) {
; CHECK-LABEL: define void @urem_fold(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK:  [[VECTOR_BODY:.*:]]
; CHECK:    [[TMP3:%.*]] = and i64 [[INDEX:%.*]], 15, !dbg [[DBG15:![0-9]+]]
; CHECK:  [[LOOP:.*:]]
; CHECK:    [[REM:%.*]] = urem i64 [[IV:%.*]], 16, !dbg [[DBG15]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %rem = urem i64 %iv, 16, !dbg !41
  %arrayidx = getelementptr inbounds nuw [4 x i8], ptr %src, i64 %rem
  %load1 = load i32, ptr %arrayidx, align 4
  %arrayidx2 = getelementptr inbounds nuw [4 x i8], ptr %dst, i64 %iv
  %load2 = load i32, ptr %arrayidx2, align 4
  %add = add nsw i32 %load2, %load1
  store i32 %add, ptr %arrayidx2, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %n
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret void

}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8, !9, !10, !11, !12, !13, !14}

!0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, producer: "clang version 24.0.0git (clang 806c5785d0f74945aad72ec30ed5dadc5ca09b61)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/tmp/foo.c", directory: "/tmp/llvm/build", checksumkind: CSK_MD5, checksum: "6435fcec96d9b5a24bd87da177a1d409")
!2 = !{i32 7, !"Dwarf Version", i32 5}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 1, !"ptrauth-elf-got", i32 0}
!5 = !{i32 1, !"ptrauth-init-fini", i32 0}
!6 = !{i32 1, !"ptrauth-init-fini-address-discrimination", i32 0}
!7 = !{i32 1, !"ptrauth-sign-personality", i32 0}
!8 = !{i32 1, !"aarch64-elf-pauthabi-platform", i32 268435458}
!9 = !{i32 1, !"aarch64-elf-pauthabi-version", i32 0}
!10 = !{i32 8, !"PIC Level", i32 2}
!11 = !{i32 7, !"PIE Level", i32 2}
!12 = !{i32 7, !"uwtable", i32 2}
!13 = !{i32 7, !"frame-pointer", i32 4}
!14 = !{i32 7, !"debug-info-assignment-tracking", i1 true}
!21 = distinct !DISubprogram(name: "foo", scope: !22, file: !22, line: 3, type: !23, scopeLine: 3, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !27, keyInstructions: true)
!22 = !DIFile(filename: "/tmp/foo.c", directory: "", checksumkind: CSK_MD5, checksum: "6435fcec96d9b5a24bd87da177a1d409")
!23 = !DISubroutineType(types: !24)
!24 = !{null, !25, !25, !26}
!25 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !26, size: 64)
!26 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!27 = !{!28, !29, !30, !31}
!28 = !DILocalVariable(name: "dst", arg: 1, scope: !21, file: !22, line: 3, type: !25)
!29 = !DILocalVariable(name: "src", arg: 2, scope: !21, file: !22, line: 3, type: !25)
!30 = !DILocalVariable(name: "n", arg: 3, scope: !21, file: !22, line: 3, type: !26)
!31 = !DILocalVariable(name: "i", scope: !32, file: !22, line: 4, type: !26)
!32 = distinct !DILexicalBlock(scope: !21, file: !22, line: 4, column: 3)
!36 = distinct !DILexicalBlock(scope: !32, file: !22, line: 4, column: 3)
!41 = !DILocation(line: 5, column: 21, scope: !42)
!42 = distinct !DILexicalBlock(scope: !36, file: !22, line: 4, column: 31)
