; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^vector.memcheck:" --version 6
; RUN: opt -passes=loop-vectorize -force-vector-width=2 -force-vector-interleave=1 -S < %s | FileCheck %s

; SCEV checks are cheap, due to stride being speculated.

define void @foo(ptr %pout, ptr %pin, i64 %val0, i64 %val1, i64 %val2) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: ptr [[POUT:%.*]], ptr [[PIN:%.*]], i64 [[VAL0:%.*]], i64 [[VAL1:%.*]], i64 [[VAL2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr double, ptr [[PIN]], i64 [[VAL0]]
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[VAL1]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[VAL1]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 3
; CHECK-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[VAL1]], i64 1)
; CHECK-NEXT:    [[TMP4:%.*]] = shl i64 [[SMAX]], 3
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[POUT]], i64 [[TMP5]]
; CHECK-NEXT:    [[TMP6:%.*]] = shl i64 [[VAL1]], 3
; CHECK-NEXT:    [[TMP7:%.*]] = shl i64 [[VAL0]], 3
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[TMP7]], [[TMP4]]
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[PIN]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i8, ptr [[PIN]], i64 [[TMP9]]
; CHECK-NEXT:    br label %[[LOOP1_HEADER:.*]]
; CHECK:       [[LOOP1_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], [[LOOP1_LATCH:%.*]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[MUL0:%.*]] = mul nsw i64 [[I]], [[VAL2]]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds double, ptr [[TMP0]], i64 [[MUL0]]
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i64 [[I]], [[VAL1]]
; CHECK-NEXT:    [[TMP10:%.*]] = call i64 @llvm.smax.i64(i64 [[VAL1]], i64 1)
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP10]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[VAL2]], 1
; CHECK-NEXT:    br i1 [[IDENT_CHECK]], [[SCALAR_PH]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
;
entry:
  %0 = getelementptr double, ptr %pin, i64 %val0
  br label %loop1.header

loop1.header:
  %i = phi i64 [ %i.next, %loop1.latch ], [ 0, %entry ]
  %mul0 = mul nsw i64 %i, %val2
  %arrayidx0 = getelementptr inbounds double, ptr %0, i64 %mul0
  %mul1 = mul nsw i64 %i, %val1
  br label %loop2.header

loop2.header:
  %j = phi i64 [ 0, %loop1.header ], [ %j.next, %loop2.header ]
  %1 = load double, ptr %arrayidx0, align 8
  %arrayidx1 = getelementptr inbounds double, ptr %0, i64 %j
  %2 = load double, ptr %arrayidx1, align 8
  %sum = fadd contract double %1, %2
  %3 = getelementptr double, ptr %pout, i64 %mul1
  %arrayidx2 = getelementptr inbounds double, ptr %3, i64 %j
  store double %sum, ptr %arrayidx2, align 8
  %j.next = add nuw nsw i64 %j, 1
  %cmp = icmp slt i64 %j.next, %val1
  br i1 %cmp, label %loop2.header, label %loop1.latch

loop1.latch:
  %i.next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %val1
  br i1 %exitcond, label %exit, label %loop1.header

exit:
  ret void
}

define void @bar(ptr %pout, ptr %pin, i64 %val0, i64 %val1, i64 %val2) {
; CHECK-LABEL: define void @bar(
; CHECK-SAME: ptr [[POUT:%.*]], ptr [[PIN:%.*]], i64 [[VAL0:%.*]], i64 [[VAL1:%.*]], i64 [[VAL2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr double, ptr [[PIN]], i64 [[VAL0]]
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[VAL1]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[VAL1]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 3
; CHECK-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[VAL1]], i64 1)
; CHECK-NEXT:    [[TMP4:%.*]] = shl i64 [[SMAX]], 3
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[POUT]], i64 [[TMP5]]
; CHECK-NEXT:    [[TMP6:%.*]] = shl i64 [[VAL1]], 3
; CHECK-NEXT:    [[TMP7:%.*]] = shl i64 [[VAL0]], 3
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[TMP7]], [[TMP4]]
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[PIN]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i8, ptr [[PIN]], i64 [[TMP9]]
; CHECK-NEXT:    br label %[[LOOP1_HEADER:.*]]
; CHECK:       [[LOOP1_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], [[LOOP1_LATCH:%.*]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[MUL0:%.*]] = mul nsw i64 [[I]], [[VAL2]]
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i64 [[I]], [[VAL1]]
; CHECK-NEXT:    [[TMP10:%.*]] = call i64 @llvm.smax.i64(i64 [[VAL1]], i64 1)
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP10]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], [[SCALAR_PH:label %.*]], label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[VAL2]], 1
; CHECK-NEXT:    br i1 [[IDENT_CHECK]], [[SCALAR_PH]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
;
entry:
  %0 = getelementptr double, ptr %pin, i64 %val0
  br label %loop1.header

loop1.header:
  %i = phi i64 [ %i.next, %loop1.latch ], [ 0, %entry ]
  %mul0 = mul nsw i64 %i, %val2
  %mul1 = mul nsw i64 %i, %val1
  br label %loop2.header

loop2.header:
  %j = phi i64 [ 0, %loop1.header ], [ %j.next, %loop2.header ]
  %arrayidx0 = getelementptr inbounds double, ptr %0, i64 %mul0
  %1 = load double, ptr %arrayidx0, align 8
  %arrayidx1 = getelementptr inbounds double, ptr %0, i64 %j
  %2 = load double, ptr %arrayidx1, align 8
  %sum = fadd contract double %1, %2
  %3 = getelementptr double, ptr %pout, i64 %mul1
  %arrayidx2 = getelementptr inbounds double, ptr %3, i64 %j
  store double %sum, ptr %arrayidx2, align 8
  %j.next = add nuw nsw i64 %j, 1
  %cmp = icmp slt i64 %j.next, %val1
  br i1 %cmp, label %loop2.header, label %loop1.latch

loop1.latch:
  %i.next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %val1
  br i1 %exitcond, label %exit, label %loop1.header

exit:
  ret void
}
