; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='thinlto-pre-link<O2>' %s | FileCheck %s --check-prefix=PRELINK
; RUN: opt -S -passes='lto-pre-link<O2>' %s | FileCheck %s --check-prefix=PRELINK
; RUN: opt -S -passes='thinlto<O2>' %s | FileCheck %s --check-prefix=POSTLINK
; RUN: opt -S -passes='lto<O2>' %s | FileCheck %s --check-prefix=POSTLINK

; Check that the LTO pre-link pipelines defer full unrolling when a loop
; contains a call that may be inlined at link time, while the post-link
; pipelines fully unroll it.

declare void @callee(i32)

define void @caller() {
; PRELINK-LABEL: define void @caller(
; PRELINK-SAME: ) local_unnamed_addr !guid [[META0:![0-9]+]] {
; PRELINK-NEXT:  [[ENTRY:.*]]:
; PRELINK-NEXT:    br label %[[LOOP:.*]]
; PRELINK:       [[LOOP]]:
; PRELINK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[LOOP]] ]
; PRELINK-NEXT:    tail call void @callee(i32 [[IV]])
; PRELINK-NEXT:    [[INC]] = add nuw nsw i32 [[IV]], 1
; PRELINK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[INC]], 4
; PRELINK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; PRELINK:       [[EXIT]]:
; PRELINK-NEXT:    ret void
;
; POSTLINK-LABEL: define void @caller() local_unnamed_addr {
; POSTLINK-NEXT:  [[ENTRY:.*:]]
; POSTLINK-NEXT:    tail call void @callee(i32 0)
; POSTLINK-NEXT:    tail call void @callee(i32 1)
; POSTLINK-NEXT:    tail call void @callee(i32 2)
; POSTLINK-NEXT:    tail call void @callee(i32 3)
; POSTLINK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %inc, %loop ]
  call void @callee(i32 %iv)
  %inc = add i32 %iv, 1
  %done = icmp eq i32 %inc, 4
  br i1 %done, label %exit, label %loop

exit:
  ret void
}
;.
; PRELINK: [[META0]] = !{i64 -1768971689307247648}
;.
