; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx92 | FileCheck %s
; RUN: %if ptxas-sm_90 && ptxas-isa-9.2 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx92 | %ptxas-verify -arch=sm_90 %}

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.u64(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)

define void @cp_async_bulk_reduce_s2g_ptx92(ptr addrspace(3) %src, ptr addrspace(1) %dst, i32 %size, i64 %ch) {
; CHECK-LABEL: cp_async_bulk_reduce_s2g_ptx92(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [cp_async_bulk_reduce_s2g_ptx92_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [cp_async_bulk_reduce_s2g_ptx92_param_1];
; CHECK-NEXT:    ld.param.b32 %r1, [cp_async_bulk_reduce_s2g_ptx92_param_2];
; CHECK-NEXT:    cp.reduce.async.bulk.global.shared::cta.bulk_group.add.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    ld.param.b64 %rd3, [cp_async_bulk_reduce_s2g_ptx92_param_3];
; CHECK-NEXT:    cp.reduce.async.bulk.global.shared::cta.bulk_group.L2::cache_hint.max.u64 [%rd2], [%rd1], %r1, %rd3;
; CHECK-NEXT:    ret;
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 2, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u64(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 7, i32 2, i64 %ch, i1 1)
  ret void
}
