; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx93 | FileCheck %s
; RUN: %if ptxas-sm_90 && ptxas-isa-9.3 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx93 | %ptxas-verify -arch=sm_90 %}

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.f16(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.bf16(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.b32(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.s32(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.b64(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.u64(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.s64(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.f32(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)
declare void @llvm.nvvm.cp.async.bulk.reduce.s2g.f64(ptr addrspace(1), ptr addrspace(3), i32, i32 immarg, i32 immarg, i64, i1 immarg)

define void @cp_async_bulk_reduce_s2g(ptr addrspace(3) %src, ptr addrspace(1) %dst, i32 %size, i64 %ch) {
; CHECK-LABEL: cp_async_bulk_reduce_s2g(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [cp_async_bulk_reduce_s2g_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [cp_async_bulk_reduce_s2g_param_1];
; CHECK-NEXT:    ld.param.b32 %r1, [cp_async_bulk_reduce_s2g_param_2];
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.sys.global.shared::cta.bulk_group.add.noftz.f16 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cta.global.shared::cta.bulk_group.min.bf16 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cluster.global.shared::cta.bulk_group.and.b32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    ld.param.b64 %rd3, [cp_async_bulk_reduce_s2g_param_3];
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.gpu.global.shared::cta.bulk_group.xor.b32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.sys.global.shared::cta.bulk_group.L2::cache_hint.or.b64 [%rd2], [%rd1], %r1, %rd3;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cta.global.shared::cta.bulk_group.add.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cluster.global.shared::cta.bulk_group.inc.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.gpu.global.shared::cta.bulk_group.dec.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.sys.global.shared::cta.bulk_group.min.s32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cta.global.shared::cta.bulk_group.max.u64 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cluster.global.shared::cta.bulk_group.min.s64 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.gpu.global.shared::cta.bulk_group.add.f32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.sys.global.shared::cta.bulk_group.L2::cache_hint.add.f64 [%rd2], [%rd1], %r1, %rd3;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cta.global.shared::cta.bulk_group.add.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.cluster.global.shared::cta.bulk_group.add.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.gpu.global.shared::cta.bulk_group.add.u32 [%rd2], [%rd1], %r1;
; CHECK-NEXT:    cp.reduce.async.bulk.relaxed.sys.global.shared::cta.bulk_group.L2::cache_hint.add.u32 [%rd2], [%rd1], %r1, %rd3;
; CHECK-NEXT:    ret;
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.f16(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 2, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.bf16(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 6, i32 1, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.b32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 0, i32 3, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.b32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 2, i32 0, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.b64(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 1, i32 2, i64 %ch, i1 1)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 1, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 4, i32 3, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 5, i32 0, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.s32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 6, i32 2, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u64(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 7, i32 1, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.s64(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 6, i32 3, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.f32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 0, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.f64(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 2, i64 %ch, i1 1)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 1, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 3, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 0, i64 %ch, i1 0)
  tail call void @llvm.nvvm.cp.async.bulk.reduce.s2g.u32(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i32 3, i32 2, i64 %ch, i1 1)
  ret void
}
