; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgpu11.00 -passes=amdgpu-attributor < %s | llc | FileCheck %s

; This function uses scratch_store to spill some values to the stack. While
; these stores are potentially outstanding it should not send the DEALLOC_VGPRS
; message.

define amdgpu_kernel void @f(ptr %ptr, i32 %arg) "amdgpu-flat-work-group-size"="64,64" {
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %gep = getelementptr i32, ptr %ptr, i32 %tid
  %val = load i32, ptr %gep
  call void asm "; clobber", "~{v[0:31]},~{v[32:63]},~{v[64:95]},~{v[96:127]},~{v[128:159]},~{v[160:191]},~{v[192:223]},~{v[224:255]},~{memory}" ()
  %cond = trunc i32 %arg to i1
  br i1 %cond, label %true, label %false
true:
  store i32 %val, ptr %gep
  br label %false
false:
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
