; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; Cost-model coverage for the per-shape masked gather/scatter overheads.
;
; ZNVER4 / ZNVER5 carry TuningPreferGSCostTable and have AVX-512, so
; getGSVectorCost reads the measured hardware cost from the schedule model
; (which stays honest for llvm-mca) and adds the per-shape break-even overhead
; from the TTI tables on top.
; ZNVER3 lacks AVX-512, so masked gather is scalarised; its numbers are the
; unchanged scalar fallback, kept only to show no regression on pre-AVX-512 Zen.
; SKX is a non-Zen AVX-512 baseline: not gated into the schedule-model path, so
; it keeps the generic flat overhead and its numbers are unchanged.
;
; RUN: opt < %s -S -mtriple=x86_64-unknown-linux-gnu -passes="print<cost-model>" 2>&1 -disable-output -cost-kind=throughput -mcpu=znver4 | FileCheck %s --check-prefix=ZNVER4
; RUN: opt < %s -S -mtriple=x86_64-unknown-linux-gnu -passes="print<cost-model>" 2>&1 -disable-output -cost-kind=throughput -mcpu=znver5 | FileCheck %s --check-prefix=ZNVER5
; RUN: opt < %s -S -mtriple=x86_64-unknown-linux-gnu -passes="print<cost-model>" 2>&1 -disable-output -cost-kind=throughput -mcpu=znver3 | FileCheck %s --check-prefix=ZNVER3
; RUN: opt < %s -S -mtriple=x86_64-unknown-linux-gnu -passes="print<cost-model>" 2>&1 -disable-output -cost-kind=throughput -mcpu=skx    | FileCheck %s --check-prefix=SKX

;------------------------------------------------------------------------------
; Masked gather - i32 element type
;------------------------------------------------------------------------------

define <2 x i32> @gather_v2i32(<2 x ptr> %ptrs, <2 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v2i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v = call <2 x i32> @llvm.masked.gather.v2i32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x i32> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i32> %v
;
; ZNVER5-LABEL: 'gather_v2i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v = call <2 x i32> @llvm.masked.gather.v2i32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x i32> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i32> %v
;
; ZNVER3-LABEL: 'gather_v2i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x i32> @llvm.masked.gather.v2i32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x i32> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i32> %v
;
; SKX-LABEL: 'gather_v2i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v = call <2 x i32> @llvm.masked.gather.v2i32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x i32> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i32> %v
;
  %v = call <2 x i32> @llvm.masked.gather.v2i32.v2p0(<2 x ptr> %ptrs, i32 4, <2 x i1> %mask, <2 x i32> undef)
  ret <2 x i32> %v
}

define <4 x i32> @gather_v4i32(<4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v4i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %v = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x i32> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i32> %v
;
; ZNVER5-LABEL: 'gather_v4i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %v = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x i32> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i32> %v
;
; ZNVER3-LABEL: 'gather_v4i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 14 for instruction: %v = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x i32> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i32> %v
;
; SKX-LABEL: 'gather_v4i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x i32> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i32> %v
;
  %v = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> %ptrs, i32 4, <4 x i1> %mask, <4 x i32> undef)
  ret <4 x i32> %v
}

define <8 x i32> @gather_v8i32(<8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v8i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: %v = call <8 x i32> @llvm.masked.gather.v8i32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x i32> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i32> %v
;
; ZNVER5-LABEL: 'gather_v8i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: %v = call <8 x i32> @llvm.masked.gather.v8i32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x i32> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i32> %v
;
; ZNVER3-LABEL: 'gather_v8i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 28 for instruction: %v = call <8 x i32> @llvm.masked.gather.v8i32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x i32> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i32> %v
;
; SKX-LABEL: 'gather_v8i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: %v = call <8 x i32> @llvm.masked.gather.v8i32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x i32> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i32> %v
;
  %v = call <8 x i32> @llvm.masked.gather.v8i32.v8p0(<8 x ptr> %ptrs, i32 4, <8 x i1> %mask, <8 x i32> undef)
  ret <8 x i32> %v
}

define <16 x i32> @gather_v16i32(<16 x ptr> %ptrs, <16 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v16i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: %v = call <16 x i32> @llvm.masked.gather.v16i32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x i32> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x i32> %v
;
; ZNVER5-LABEL: 'gather_v16i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: %v = call <16 x i32> @llvm.masked.gather.v16i32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x i32> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x i32> %v
;
; ZNVER3-LABEL: 'gather_v16i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 55 for instruction: %v = call <16 x i32> @llvm.masked.gather.v16i32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x i32> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x i32> %v
;
; SKX-LABEL: 'gather_v16i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 20 for instruction: %v = call <16 x i32> @llvm.masked.gather.v16i32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x i32> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x i32> %v
;
  %v = call <16 x i32> @llvm.masked.gather.v16i32.v16p0(<16 x ptr> %ptrs, i32 4, <16 x i1> %mask, <16 x i32> undef)
  ret <16 x i32> %v
}

;------------------------------------------------------------------------------
; Masked gather - i64 element type
;------------------------------------------------------------------------------

define <2 x i64> @gather_v2i64(<2 x ptr> %ptrs, <2 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v2i64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v = call <2 x i64> @llvm.masked.gather.v2i64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x i64> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i64> %v
;
; ZNVER5-LABEL: 'gather_v2i64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v = call <2 x i64> @llvm.masked.gather.v2i64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x i64> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i64> %v
;
; ZNVER3-LABEL: 'gather_v2i64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x i64> @llvm.masked.gather.v2i64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x i64> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i64> %v
;
; SKX-LABEL: 'gather_v2i64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v = call <2 x i64> @llvm.masked.gather.v2i64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x i64> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x i64> %v
;
  %v = call <2 x i64> @llvm.masked.gather.v2i64.v2p0(<2 x ptr> %ptrs, i32 8, <2 x i1> %mask, <2 x i64> undef)
  ret <2 x i64> %v
}

define <4 x i64> @gather_v4i64(<4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v4i64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 14 for instruction: %v = call <4 x i64> @llvm.masked.gather.v4i64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x i64> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i64> %v
;
; ZNVER5-LABEL: 'gather_v4i64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 14 for instruction: %v = call <4 x i64> @llvm.masked.gather.v4i64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x i64> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i64> %v
;
; ZNVER3-LABEL: 'gather_v4i64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 15 for instruction: %v = call <4 x i64> @llvm.masked.gather.v4i64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x i64> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i64> %v
;
; SKX-LABEL: 'gather_v4i64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v = call <4 x i64> @llvm.masked.gather.v4i64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x i64> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x i64> %v
;
  %v = call <4 x i64> @llvm.masked.gather.v4i64.v4p0(<4 x ptr> %ptrs, i32 8, <4 x i1> %mask, <4 x i64> undef)
  ret <4 x i64> %v
}

define <8 x i64> @gather_v8i64(<8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v8i64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 30 for instruction: %v = call <8 x i64> @llvm.masked.gather.v8i64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x i64> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i64> %v
;
; ZNVER5-LABEL: 'gather_v8i64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 30 for instruction: %v = call <8 x i64> @llvm.masked.gather.v8i64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x i64> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i64> %v
;
; ZNVER3-LABEL: 'gather_v8i64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 29 for instruction: %v = call <8 x i64> @llvm.masked.gather.v8i64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x i64> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i64> %v
;
; SKX-LABEL: 'gather_v8i64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: %v = call <8 x i64> @llvm.masked.gather.v8i64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x i64> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x i64> %v
;
  %v = call <8 x i64> @llvm.masked.gather.v8i64.v8p0(<8 x ptr> %ptrs, i32 8, <8 x i1> %mask, <8 x i64> undef)
  ret <8 x i64> %v
}

;------------------------------------------------------------------------------
; Masked gather - f32 element type
;------------------------------------------------------------------------------

define <2 x float> @gather_v2f32(<2 x ptr> %ptrs, <2 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v2f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x float> @llvm.masked.gather.v2f32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x float> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x float> %v
;
; ZNVER5-LABEL: 'gather_v2f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x float> @llvm.masked.gather.v2f32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x float> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x float> %v
;
; ZNVER3-LABEL: 'gather_v2f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v = call <2 x float> @llvm.masked.gather.v2f32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x float> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x float> %v
;
; SKX-LABEL: 'gather_v2f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x float> @llvm.masked.gather.v2f32.v2p0(<2 x ptr> align 4 %ptrs, <2 x i1> %mask, <2 x float> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x float> %v
;
  %v = call <2 x float> @llvm.masked.gather.v2f32.v2p0(<2 x ptr> %ptrs, i32 4, <2 x i1> %mask, <2 x float> undef)
  ret <2 x float> %v
}

define <4 x float> @gather_v4f32(<4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v4f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %v = call <4 x float> @llvm.masked.gather.v4f32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x float> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x float> %v
;
; ZNVER5-LABEL: 'gather_v4f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %v = call <4 x float> @llvm.masked.gather.v4f32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x float> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x float> %v
;
; ZNVER3-LABEL: 'gather_v4f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 13 for instruction: %v = call <4 x float> @llvm.masked.gather.v4f32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x float> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x float> %v
;
; SKX-LABEL: 'gather_v4f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v = call <4 x float> @llvm.masked.gather.v4f32.v4p0(<4 x ptr> align 4 %ptrs, <4 x i1> %mask, <4 x float> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x float> %v
;
  %v = call <4 x float> @llvm.masked.gather.v4f32.v4p0(<4 x ptr> %ptrs, i32 4, <4 x i1> %mask, <4 x float> undef)
  ret <4 x float> %v
}

define <8 x float> @gather_v8f32(<8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v8f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: %v = call <8 x float> @llvm.masked.gather.v8f32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x float> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x float> %v
;
; ZNVER5-LABEL: 'gather_v8f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: %v = call <8 x float> @llvm.masked.gather.v8f32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x float> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x float> %v
;
; ZNVER3-LABEL: 'gather_v8f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 26 for instruction: %v = call <8 x float> @llvm.masked.gather.v8f32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x float> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x float> %v
;
; SKX-LABEL: 'gather_v8f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: %v = call <8 x float> @llvm.masked.gather.v8f32.v8p0(<8 x ptr> align 4 %ptrs, <8 x i1> %mask, <8 x float> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x float> %v
;
  %v = call <8 x float> @llvm.masked.gather.v8f32.v8p0(<8 x ptr> %ptrs, i32 4, <8 x i1> %mask, <8 x float> undef)
  ret <8 x float> %v
}

define <16 x float> @gather_v16f32(<16 x ptr> %ptrs, <16 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v16f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: %v = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x float> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x float> %v
;
; ZNVER5-LABEL: 'gather_v16f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: %v = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x float> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x float> %v
;
; ZNVER3-LABEL: 'gather_v16f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 51 for instruction: %v = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x float> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x float> %v
;
; SKX-LABEL: 'gather_v16f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 20 for instruction: %v = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> align 4 %ptrs, <16 x i1> %mask, <16 x float> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <16 x float> %v
;
  %v = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> %ptrs, i32 4, <16 x i1> %mask, <16 x float> undef)
  ret <16 x float> %v
}

;------------------------------------------------------------------------------
; Masked gather - f64 element type
;------------------------------------------------------------------------------

define <2 x double> @gather_v2f64(<2 x ptr> %ptrs, <2 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v2f64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x double> @llvm.masked.gather.v2f64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x double> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x double> %v
;
; ZNVER5-LABEL: 'gather_v2f64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x double> @llvm.masked.gather.v2f64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x double> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x double> %v
;
; ZNVER3-LABEL: 'gather_v2f64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v = call <2 x double> @llvm.masked.gather.v2f64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x double> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x double> %v
;
; SKX-LABEL: 'gather_v2f64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v = call <2 x double> @llvm.masked.gather.v2f64.v2p0(<2 x ptr> align 8 %ptrs, <2 x i1> %mask, <2 x double> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <2 x double> %v
;
  %v = call <2 x double> @llvm.masked.gather.v2f64.v2p0(<2 x ptr> %ptrs, i32 8, <2 x i1> %mask, <2 x double> undef)
  ret <2 x double> %v
}

define <4 x double> @gather_v4f64(<4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v4f64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %v = call <4 x double> @llvm.masked.gather.v4f64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x double> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x double> %v
;
; ZNVER5-LABEL: 'gather_v4f64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %v = call <4 x double> @llvm.masked.gather.v4f64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x double> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x double> %v
;
; ZNVER3-LABEL: 'gather_v4f64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 13 for instruction: %v = call <4 x double> @llvm.masked.gather.v4f64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x double> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x double> %v
;
; SKX-LABEL: 'gather_v4f64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v = call <4 x double> @llvm.masked.gather.v4f64.v4p0(<4 x ptr> align 8 %ptrs, <4 x i1> %mask, <4 x double> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <4 x double> %v
;
  %v = call <4 x double> @llvm.masked.gather.v4f64.v4p0(<4 x ptr> %ptrs, i32 8, <4 x i1> %mask, <4 x double> undef)
  ret <4 x double> %v
}

define <8 x double> @gather_v8f64(<8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'gather_v8f64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 25 for instruction: %v = call <8 x double> @llvm.masked.gather.v8f64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x double> undef)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x double> %v
;
; ZNVER5-LABEL: 'gather_v8f64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 25 for instruction: %v = call <8 x double> @llvm.masked.gather.v8f64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x double> undef)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x double> %v
;
; ZNVER3-LABEL: 'gather_v8f64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 25 for instruction: %v = call <8 x double> @llvm.masked.gather.v8f64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x double> undef)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x double> %v
;
; SKX-LABEL: 'gather_v8f64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: %v = call <8 x double> @llvm.masked.gather.v8f64.v8p0(<8 x ptr> align 8 %ptrs, <8 x i1> %mask, <8 x double> undef)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret <8 x double> %v
;
  %v = call <8 x double> @llvm.masked.gather.v8f64.v8p0(<8 x ptr> %ptrs, i32 8, <8 x i1> %mask, <8 x double> undef)
  ret <8 x double> %v
}

;------------------------------------------------------------------------------
; Masked scatter - i32 element type
;------------------------------------------------------------------------------

define void @scatter_v4i32(<4 x i32> %src, <4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v4i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 18 for instruction: call void @llvm.masked.scatter.v4i32.v4p0(<4 x i32> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v4i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 18 for instruction: call void @llvm.masked.scatter.v4i32.v4p0(<4 x i32> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v4i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 14 for instruction: call void @llvm.masked.scatter.v4i32.v4p0(<4 x i32> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v4i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: call void @llvm.masked.scatter.v4i32.v4p0(<4 x i32> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v4i32.v4p0(<4 x i32> %src, <4 x ptr> %ptrs, i32 4, <4 x i1> %mask)
  ret void
}

define void @scatter_v8i32(<8 x i32> %src, <8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v8i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: call void @llvm.masked.scatter.v8i32.v8p0(<8 x i32> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v8i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: call void @llvm.masked.scatter.v8i32.v8p0(<8 x i32> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v8i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 28 for instruction: call void @llvm.masked.scatter.v8i32.v8p0(<8 x i32> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v8i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: call void @llvm.masked.scatter.v8i32.v8p0(<8 x i32> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v8i32.v8p0(<8 x i32> %src, <8 x ptr> %ptrs, i32 4, <8 x i1> %mask)
  ret void
}

define void @scatter_v16i32(<16 x i32> %src, <16 x ptr> %ptrs, <16 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v16i32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: call void @llvm.masked.scatter.v16i32.v16p0(<16 x i32> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v16i32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: call void @llvm.masked.scatter.v16i32.v16p0(<16 x i32> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v16i32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 55 for instruction: call void @llvm.masked.scatter.v16i32.v16p0(<16 x i32> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v16i32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 20 for instruction: call void @llvm.masked.scatter.v16i32.v16p0(<16 x i32> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v16i32.v16p0(<16 x i32> %src, <16 x ptr> %ptrs, i32 4, <16 x i1> %mask)
  ret void
}

;------------------------------------------------------------------------------
; Masked scatter - i64 element type
;------------------------------------------------------------------------------

define void @scatter_v4i64(<4 x i64> %src, <4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v4i64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 15 for instruction: call void @llvm.masked.scatter.v4i64.v4p0(<4 x i64> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v4i64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 15 for instruction: call void @llvm.masked.scatter.v4i64.v4p0(<4 x i64> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v4i64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 15 for instruction: call void @llvm.masked.scatter.v4i64.v4p0(<4 x i64> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v4i64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: call void @llvm.masked.scatter.v4i64.v4p0(<4 x i64> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v4i64.v4p0(<4 x i64> %src, <4 x ptr> %ptrs, i32 8, <4 x i1> %mask)
  ret void
}

define void @scatter_v8i64(<8 x i64> %src, <8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v8i64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 31 for instruction: call void @llvm.masked.scatter.v8i64.v8p0(<8 x i64> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v8i64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 31 for instruction: call void @llvm.masked.scatter.v8i64.v8p0(<8 x i64> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v8i64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 29 for instruction: call void @llvm.masked.scatter.v8i64.v8p0(<8 x i64> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v8i64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: call void @llvm.masked.scatter.v8i64.v8p0(<8 x i64> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v8i64.v8p0(<8 x i64> %src, <8 x ptr> %ptrs, i32 8, <8 x i1> %mask)
  ret void
}

;------------------------------------------------------------------------------
; Masked scatter - f32 element type
;------------------------------------------------------------------------------

define void @scatter_v4f32(<4 x float> %src, <4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v4f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 18 for instruction: call void @llvm.masked.scatter.v4f32.v4p0(<4 x float> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v4f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 18 for instruction: call void @llvm.masked.scatter.v4f32.v4p0(<4 x float> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v4f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 13 for instruction: call void @llvm.masked.scatter.v4f32.v4p0(<4 x float> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v4f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: call void @llvm.masked.scatter.v4f32.v4p0(<4 x float> %src, <4 x ptr> align 4 %ptrs, <4 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v4f32.v4p0(<4 x float> %src, <4 x ptr> %ptrs, i32 4, <4 x i1> %mask)
  ret void
}

define void @scatter_v8f32(<8 x float> %src, <8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v8f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: call void @llvm.masked.scatter.v8f32.v8p0(<8 x float> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v8f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 23 for instruction: call void @llvm.masked.scatter.v8f32.v8p0(<8 x float> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v8f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 26 for instruction: call void @llvm.masked.scatter.v8f32.v8p0(<8 x float> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v8f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: call void @llvm.masked.scatter.v8f32.v8p0(<8 x float> %src, <8 x ptr> align 4 %ptrs, <8 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v8f32.v8p0(<8 x float> %src, <8 x ptr> %ptrs, i32 4, <8 x i1> %mask)
  ret void
}

define void @scatter_v16f32(<16 x float> %src, <16 x ptr> %ptrs, <16 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v16f32'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: call void @llvm.masked.scatter.v16f32.v16p0(<16 x float> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v16f32'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 46 for instruction: call void @llvm.masked.scatter.v16f32.v16p0(<16 x float> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v16f32'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 51 for instruction: call void @llvm.masked.scatter.v16f32.v16p0(<16 x float> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v16f32'
; SKX-NEXT:  Cost Model: Found an estimated cost of 20 for instruction: call void @llvm.masked.scatter.v16f32.v16p0(<16 x float> %src, <16 x ptr> align 4 %ptrs, <16 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v16f32.v16p0(<16 x float> %src, <16 x ptr> %ptrs, i32 4, <16 x i1> %mask)
  ret void
}

;------------------------------------------------------------------------------
; Masked scatter - f64 element type
;------------------------------------------------------------------------------

define void @scatter_v4f64(<4 x double> %src, <4 x ptr> %ptrs, <4 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v4f64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: call void @llvm.masked.scatter.v4f64.v4p0(<4 x double> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v4f64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: call void @llvm.masked.scatter.v4f64.v4p0(<4 x double> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v4f64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 13 for instruction: call void @llvm.masked.scatter.v4f64.v4p0(<4 x double> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v4f64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: call void @llvm.masked.scatter.v4f64.v4p0(<4 x double> %src, <4 x ptr> align 8 %ptrs, <4 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v4f64.v4p0(<4 x double> %src, <4 x ptr> %ptrs, i32 8, <4 x i1> %mask)
  ret void
}

define void @scatter_v8f64(<8 x double> %src, <8 x ptr> %ptrs, <8 x i1> %mask) {
; ZNVER4-LABEL: 'scatter_v8f64'
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 24 for instruction: call void @llvm.masked.scatter.v8f64.v8p0(<8 x double> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; ZNVER4-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER5-LABEL: 'scatter_v8f64'
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 24 for instruction: call void @llvm.masked.scatter.v8f64.v8p0(<8 x double> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; ZNVER5-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZNVER3-LABEL: 'scatter_v8f64'
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 25 for instruction: call void @llvm.masked.scatter.v8f64.v8p0(<8 x double> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; ZNVER3-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SKX-LABEL: 'scatter_v8f64'
; SKX-NEXT:  Cost Model: Found an estimated cost of 10 for instruction: call void @llvm.masked.scatter.v8f64.v8p0(<8 x double> %src, <8 x ptr> align 8 %ptrs, <8 x i1> %mask)
; SKX-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.masked.scatter.v8f64.v8p0(<8 x double> %src, <8 x ptr> %ptrs, i32 8, <8 x i1> %mask)
  ret void
}
