; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --filter "Cost.of.*EXPRESSION" --version 6
; RUN: opt -passes=loop-vectorize -enable-epilogue-vectorization=false \
; RUN:     -debug-only=loop-vectorize -disable-output < %s 2>&1 | FileCheck %s

; REQUIRES: asserts
target triple = "x86_64-unknown-linux-gnu"

define i32 @dot_s8u8_vf64(ptr readonly %a, ptr readonly %b) #0 {
; CHECK-LABEL: 'dot_s8u8_vf64'
; CHECK:  Cost of 1 for VF 64: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> zext to i32))
; CHECK:  Cost of 1 for VF 64: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> zext to i32))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr inbounds i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul nsw i32 %ext.a, %ext.b
  %sum.next = add nsw i32 %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !0

exit:
  ret i32 %sum.next
}

define i32 @dot_s8s8_vf64(ptr readonly %a, ptr readonly %b) #1 {
; CHECK-LABEL: 'dot_s8s8_vf64'
; CHECK:  Cost of 1 for VF 64: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> sext to i32))
; CHECK:  Cost of 1 for VF 64: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> sext to i32))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr inbounds i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul nsw i32 %ext.a, %ext.b
  %sum.next = add nsw i32 %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !1

exit:
  ret i32 %sum.next
}

define i32 @dot_u8u8_vf64(ptr readonly %a, ptr readonly %b) #1 {
; CHECK-LABEL: 'dot_u8u8_vf64'
; CHECK:  Cost of 1 for VF 64: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.add (mul (ir<%load.a> zext to i32), (ir<%load.b> zext to i32))
; CHECK:  Cost of 1 for VF 64: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.add (mul (ir<%load.a> zext to i32), (ir<%load.b> zext to i32))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr inbounds i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.a, %ext.b
  %sum.next = add i32 %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !2

exit:
  ret i32 %sum.next
}

define i32 @dot_s16s16_vf32(ptr readonly %a, ptr readonly %b) #0 {
; CHECK-LABEL: 'dot_s16s16_vf32'
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> sext to i32))
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> sext to i32))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds i16, ptr %a, i64 %iv
  %load.a = load i16, ptr %gep.a, align 2
  %ext.a = sext i16 %load.a to i32
  %gep.b = getelementptr inbounds i16, ptr %b, i64 %iv
  %load.b = load i16, ptr %gep.b, align 2
  %ext.b = sext i16 %load.b to i32
  %mul = mul nsw i32 %ext.a, %ext.b
  %sum.next = add nsw i32 %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !3

exit:
  ret i32 %sum.next
}

define i32 @dot_s16u16_vf32(ptr readonly %a, ptr readonly %b) #2 {
; CHECK-LABEL: 'dot_s16u16_vf32'
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> zext to i32))
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.add (mul nsw (ir<%load.a> sext to i32), (ir<%load.b> zext to i32))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds i16, ptr %a, i64 %iv
  %load.a = load i16, ptr %gep.a, align 2
  %ext.a = sext i16 %load.a to i32
  %gep.b = getelementptr inbounds i16, ptr %b, i64 %iv
  %load.b = load i16, ptr %gep.b, align 2
  %ext.b = zext i16 %load.b to i32
  %mul = mul nsw i32 %ext.a, %ext.b
  %sum.next = add nsw i32 %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !4

exit:
  ret i32 %sum.next
}

define i32 @dot_u16u16_vf32(ptr readonly %a, ptr readonly %b) #2 {
; CHECK-LABEL: 'dot_u16u16_vf32'
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.add (mul (ir<%load.a> zext to i32), (ir<%load.b> zext to i32))
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.add (mul (ir<%load.a> zext to i32), (ir<%load.b> zext to i32))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds i16, ptr %a, i64 %iv
  %load.a = load i16, ptr %gep.a, align 2
  %ext.a = zext i16 %load.a to i32
  %gep.b = getelementptr inbounds i16, ptr %b, i64 %iv
  %load.b = load i16, ptr %gep.b, align 2
  %ext.b = zext i16 %load.b to i32
  %mul = mul i32 %ext.a, %ext.b
  %sum.next = add i32 %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !5

exit:
  ret i32 %sum.next
}

define float @dot_bf16_vf32(ptr readonly %a, ptr readonly %b) #3 {
; CHECK-LABEL: 'dot_bf16_vf32'
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8:%[0-9]+]]> = ir<%sum> + partial.reduce.fadd (mul contract (ir<%load.a> fpext to float), (ir<%load.b> fpext to float))
; CHECK:  Cost of 1 for VF 32: EXPRESSION vp<[[VP8]]> = ir<%sum> + partial.reduce.fadd (mul contract (ir<%load.a> fpext to float), (ir<%load.b> fpext to float))
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi float [ 0.0, %entry ], [ %sum.next, %loop ]
  %gep.a = getelementptr inbounds bfloat, ptr %a, i64 %iv
  %load.a = load bfloat, ptr %gep.a, align 2
  %ext.a = fpext bfloat %load.a to float
  %gep.b = getelementptr inbounds bfloat, ptr %b, i64 %iv
  %load.b = load bfloat, ptr %gep.b, align 2
  %ext.b = fpext bfloat %load.b to float
  %mul = fmul contract float %ext.a, %ext.b
  %sum.next = fadd reassoc contract float %sum, %mul
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !6

exit:
  ret float %sum.next
}

attributes #0 = { "target-features"="+avx2,+avx512bw,+avx512f,+avx512vl,+avxvnni,-avx512vnni" }
attributes #1 = { "target-features"="+avx2,+avx512bw,+avx512f,+avx512vl,+avxvnniint8,-avx10.2" }
attributes #2 = { "target-features"="+avx2,+avx512bw,+avx512f,+avx512vl,+avxvnniint16,-avx10.2" }
attributes #3 = { "target-features"="+avx512bf16,+avx512bw,+avx512f,+avx512vl" }

!0 = distinct !{!0, !7, !8}
!1 = distinct !{!1, !7, !8}
!2 = distinct !{!2, !7, !8}
!3 = distinct !{!3, !7, !9}
!4 = distinct !{!4, !7, !9}
!5 = distinct !{!5, !7, !9}
!6 = distinct !{!6, !7, !9}
!7 = !{!"llvm.loop.interleave.count", i32 1}
!8 = !{!"llvm.loop.vectorize.width", i32 64}
!9 = !{!"llvm.loop.vectorize.width", i32 32}
