; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --filter "active.lane.mask" --version 6
; RUN: opt -passes=loop-vectorize -tail-folding-policy=must-fold-tail  -force-tail-folding-style=data -force-vector-width=4 -disable-output -vplan-print-after=printOptimizedVPlan %s 2>&1 | FileCheck %s --check-prefix=FIXED
; RUN: opt -passes=loop-vectorize -tail-folding-policy=must-fold-tail -force-tail-folding-style=data -force-vector-width="vscale x 4" -disable-output -vplan-print-after=printOptimizedVPlan %s 2>&1 | FileCheck %s --check-prefix=SCALABLE

; We never emit fixed-vector active.lane.masks foldable to false.
define i16 @foldable_fixed_alm(i32 %x) {
; FIXED-LABEL: VPlan for loop in 'foldable_fixed_alm'
; SCALABLE-LABEL: VPlan for loop in 'foldable_fixed_alm'
; SCALABLE:      EMIT vp<%active.lane.mask> = active lane mask vp<[[VP5:%[0-9]+]]>, ir<4>, ir<1>
; SCALABLE:    EMIT vp<[[VP7:%[0-9]+]]> = last-active-lane vp<%active.lane.mask>
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %red = phi i32 [ 0, %entry ], [ %add, %loop ]
  %t = trunc i32 %red to i16
  %add = add i32 %red, %x
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv, 3
  br i1 %ec, label %exit, label %loop

exit:
  ret i16 %t
}
