; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p \
; RUN:   -verify-machineinstrs < %s | \
; RUN:   FileCheck --check-prefixes=CHECK,RV32 %s

define zeroext i8 @zexti8_paddb(i8 zeroext %x, i8 zeroext %y) {
; CHECK-LABEL: zexti8_paddb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    padd.b a0, a1, a0
; CHECK-NEXT:    ret
entry:
  %add = add i8 %y, %x
  ret i8 %add
}

define zeroext i16 @zexti16_paddh(i16 zeroext %x, i16 zeroext %y) {
; CHECK-LABEL: zexti16_paddh:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    padd.h a0, a1, a0
; CHECK-NEXT:    ret
entry:
  %add = add i16 %y, %x
  ret i16 %add
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32: {{.*}}
