; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+f,+d -target-abi=lp64d -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64D %s
; RUN: llc -mtriple=riscv32 -mattr=+f,+d -target-abi=ilp32d -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32D %s
; RUN: llc -mtriple=riscv64 -target-abi=lp64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=riscv32 -target-abi=ilp32 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s

; RISC-V long double is fp128, so the correct libcalls for llvm.lround.f128 and
; llvm.llround.f128 are lroundl and llroundl respectively. Regression test for
; the SDAG wrongly selecting the f32 libcall (lroundf) for the i32-result
; lround on rv64.

define i32 @lround_f128(fp128 %a) nounwind {
; RV64D-LABEL: lround_f128:
; RV64D:       # %bb.0:
; RV64D-NEXT:    addi sp, sp, -16
; RV64D-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64D-NEXT:    call lroundl
; RV64D-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64D-NEXT:    addi sp, sp, 16
; RV64D-NEXT:    ret
;
; RV32D-LABEL: lround_f128:
; RV32D:       # %bb.0:
; RV32D-NEXT:    addi sp, sp, -32
; RV32D-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32D-NEXT:    lw a1, 0(a0)
; RV32D-NEXT:    lw a2, 4(a0)
; RV32D-NEXT:    lw a3, 8(a0)
; RV32D-NEXT:    lw a4, 12(a0)
; RV32D-NEXT:    addi a0, sp, 8
; RV32D-NEXT:    sw a1, 8(sp)
; RV32D-NEXT:    sw a2, 12(sp)
; RV32D-NEXT:    sw a3, 16(sp)
; RV32D-NEXT:    sw a4, 20(sp)
; RV32D-NEXT:    call lroundl
; RV32D-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32D-NEXT:    addi sp, sp, 32
; RV32D-NEXT:    ret
;
; RV64I-LABEL: lround_f128:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call lroundl
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
;
; RV32I-LABEL: lround_f128:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -32
; RV32I-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lw a1, 0(a0)
; RV32I-NEXT:    lw a2, 4(a0)
; RV32I-NEXT:    lw a3, 8(a0)
; RV32I-NEXT:    lw a4, 12(a0)
; RV32I-NEXT:    addi a0, sp, 8
; RV32I-NEXT:    sw a1, 8(sp)
; RV32I-NEXT:    sw a2, 12(sp)
; RV32I-NEXT:    sw a3, 16(sp)
; RV32I-NEXT:    sw a4, 20(sp)
; RV32I-NEXT:    call lroundl
; RV32I-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 32
; RV32I-NEXT:    ret
  %r = call i32 @llvm.lround.f128(fp128 %a)
  ret i32 %r
}

define i64 @llround_f128(fp128 %a) nounwind {
; RV64D-LABEL: llround_f128:
; RV64D:       # %bb.0:
; RV64D-NEXT:    addi sp, sp, -16
; RV64D-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64D-NEXT:    call llroundl
; RV64D-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64D-NEXT:    addi sp, sp, 16
; RV64D-NEXT:    ret
;
; RV32D-LABEL: llround_f128:
; RV32D:       # %bb.0:
; RV32D-NEXT:    addi sp, sp, -32
; RV32D-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32D-NEXT:    lw a1, 0(a0)
; RV32D-NEXT:    lw a2, 4(a0)
; RV32D-NEXT:    lw a3, 8(a0)
; RV32D-NEXT:    lw a4, 12(a0)
; RV32D-NEXT:    mv a0, sp
; RV32D-NEXT:    sw a1, 0(sp)
; RV32D-NEXT:    sw a2, 4(sp)
; RV32D-NEXT:    sw a3, 8(sp)
; RV32D-NEXT:    sw a4, 12(sp)
; RV32D-NEXT:    call llroundl
; RV32D-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32D-NEXT:    addi sp, sp, 32
; RV32D-NEXT:    ret
;
; RV64I-LABEL: llround_f128:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call llroundl
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
;
; RV32I-LABEL: llround_f128:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -32
; RV32I-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lw a1, 0(a0)
; RV32I-NEXT:    lw a2, 4(a0)
; RV32I-NEXT:    lw a3, 8(a0)
; RV32I-NEXT:    lw a4, 12(a0)
; RV32I-NEXT:    mv a0, sp
; RV32I-NEXT:    sw a1, 0(sp)
; RV32I-NEXT:    sw a2, 4(sp)
; RV32I-NEXT:    sw a3, 8(sp)
; RV32I-NEXT:    sw a4, 12(sp)
; RV32I-NEXT:    call llroundl
; RV32I-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 32
; RV32I-NEXT:    ret
  %r = call i64 @llvm.llround.f128(fp128 %a)
  ret i64 %r
}

declare i32 @llvm.lround.f128(fp128)
declare i64 @llvm.llround.f128(fp128)
