; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @udiv_max_q1(i32 %x) {
; CHECK-LABEL: @udiv_max_q1(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[TMP1:%.*]] = icmp samesign ugt i32 [[X]], 59
; CHECK-NEXT:    [[DIV:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %cmp = icmp ult i32 %x, 100
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, 60
  ret i32 %div
}

define i32 @udiv_max_q2(i32 %x) {
; CHECK-LABEL: @udiv_max_q2(
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ugt i32 [[X:%.*]], 2147483646
; CHECK-NEXT:    [[TMP2:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ugt i32 [[X]], -3
; CHECK-NEXT:    [[TMP4:%.*]] = zext i1 [[TMP3]] to i32
; CHECK-NEXT:    [[DIV:%.*]] = add nuw nsw i32 [[TMP2]], [[TMP4]]
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %div = udiv i32 %x, 2147483647
  ret i32 %div
}

define i32 @udiv_max_q2_with_assume(i32 %x) {
; CHECK-LABEL: @udiv_max_q2_with_assume(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 150
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[TMP1:%.*]] = icmp samesign ugt i32 [[X]], 59
; CHECK-NEXT:    [[TMP2:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = icmp samesign ugt i32 [[X]], 119
; CHECK-NEXT:    [[TMP4:%.*]] = zext i1 [[TMP3]] to i32
; CHECK-NEXT:    [[DIV:%.*]] = add nuw nsw i32 [[TMP2]], [[TMP4]]
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %cmp = icmp ult i32 %x, 150
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, 60
  ret i32 %div
}

declare void @llvm.assume(i1)

define i32 @udiv_max_q2_x_14(i32 %x) {
; CHECK-LABEL: @udiv_max_q2_x_14(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 15
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[TMP1:%.*]] = icmp samesign ugt i32 [[X]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = icmp samesign ugt i32 [[X]], 9
; CHECK-NEXT:    [[TMP4:%.*]] = zext i1 [[TMP3]] to i32
; CHECK-NEXT:    [[DIV:%.*]] = add nuw nsw i32 [[TMP2]], [[TMP4]]
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %cmp = icmp ult i32 %x, 15
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, 5
  ret i32 %div
}

define i32 @udiv_max_q3_x_19_unchanged(i32 %x) {
; CHECK-LABEL: @udiv_max_q3_x_19_unchanged(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[DIV:%.*]] = udiv i32 [[X]], 5
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %cmp = icmp ult i32 %x, 20
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, 5
  ret i32 %div
}

define i32 @udiv_too_large_unchanged(i32 %x) {
; CHECK-LABEL: @udiv_too_large_unchanged(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[DIV:%.*]] = udiv i32 [[X]], 5
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %cmp = icmp ult i32 %x, 100
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, 5
  ret i32 %div
}

define i32 @udiv_c_1(i32 %x) {
; CHECK-LABEL: @udiv_c_1(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 5
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 [[X]]
;
  %cmp = icmp ult i32 %x, 5
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, 1
  ret i32 %div
}

define i32 @udiv_non_const(i32 %x, i32 %y) {
; CHECK-LABEL: @udiv_non_const(
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[DIV:%.*]] = udiv i32 [[X]], [[Y:%.*]]
; CHECK-NEXT:    ret i32 [[DIV]]
;
  %cmp = icmp ult i32 %x, 10
  call void @llvm.assume(i1 %cmp)
  %div = udiv i32 %x, %y
  ret i32 %div
}
