; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes=loop-vectorize -S < %s | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64"

define double @test(i32 %0) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: i32 [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[REDUX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[BINOP:%.*]], %[[VECTOR_PH]] ]
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[NEXT_IV:%.*]], %[[VECTOR_PH]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[BINOP]] = or i64 [[REDUX]], [[TMP1]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr [8 x i8], ptr null, i64 [[TMP1]]
; CHECK-NEXT:    [[LOAD:%.*]] = load double, ptr [[GEP]], align 8
; CHECK-NEXT:    [[NEXT_IV]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV]], 1
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[EXIT:.*]], label %[[VECTOR_PH]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi i64 [ [[BINOP]], %[[VECTOR_PH]] ]
; CHECK-NEXT:    [[RET:%.*]] = uitofp i64 [[TMP3]] to double
; CHECK-NEXT:    ret double [[RET]]
;
entry:
  br label %for.body

for.body:
  %redux = phi i64 [ 0, %entry ], [ %binop, %for.body ]
  %iv = phi i64 [ 0, %entry ], [ %next.iv, %for.body ]
  %ext = zext i32 %0 to i64
  %binop = or i64 %redux, %ext
  %gep = getelementptr [8 x i8], ptr null, i64 %ext
  %load = load double, ptr %gep, align 8
  %next.iv = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv, 1
  br i1 %exitcond.not, label %exit, label %for.body

exit:
  %ret = uitofp i64 %binop to double
  ret double %ret
}
