; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64 | FileCheck %s --check-prefix=SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v2 | FileCheck %s --check-prefix=SSE42
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v3| FileCheck %s --check-prefix=AVX2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v4 | FileCheck %s --check-prefix=AVX512

; v8i64 narrowed to v64i8 - LHS masked to 8 bits, should use vpsubusb
define <8 x i64> @usubsat_v8i64_i8_narrow(<8 x i64> %x, <8 x i64> %y) nounwind {
; SSE2-LABEL: usubsat_v8i64_i8_narrow:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm8 = [255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0]
; SSE2-NEXT:    pand %xmm8, %xmm3
; SSE2-NEXT:    pand %xmm8, %xmm2
; SSE2-NEXT:    pand %xmm8, %xmm1
; SSE2-NEXT:    pand %xmm8, %xmm0
; SSE2-NEXT:    movdqa {{.*#+}} xmm8 = [18446744073709551360,18446744073709551360]
; SSE2-NEXT:    por %xmm8, %xmm4
; SSE2-NEXT:    psubusb %xmm4, %xmm0
; SSE2-NEXT:    por %xmm8, %xmm5
; SSE2-NEXT:    psubusb %xmm5, %xmm1
; SSE2-NEXT:    por %xmm8, %xmm6
; SSE2-NEXT:    psubusb %xmm6, %xmm2
; SSE2-NEXT:    por %xmm8, %xmm7
; SSE2-NEXT:    psubusb %xmm7, %xmm3
; SSE2-NEXT:    retq
;
; SSE42-LABEL: usubsat_v8i64_i8_narrow:
; SSE42:       # %bb.0:
; SSE42-NEXT:    movdqa {{.*#+}} xmm8 = [255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0]
; SSE42-NEXT:    pand %xmm8, %xmm3
; SSE42-NEXT:    pand %xmm8, %xmm2
; SSE42-NEXT:    pand %xmm8, %xmm1
; SSE42-NEXT:    pand %xmm8, %xmm0
; SSE42-NEXT:    movdqa {{.*#+}} xmm8 = [18446744073709551360,18446744073709551360]
; SSE42-NEXT:    por %xmm8, %xmm4
; SSE42-NEXT:    psubusb %xmm4, %xmm0
; SSE42-NEXT:    por %xmm8, %xmm5
; SSE42-NEXT:    psubusb %xmm5, %xmm1
; SSE42-NEXT:    por %xmm8, %xmm6
; SSE42-NEXT:    psubusb %xmm6, %xmm2
; SSE42-NEXT:    por %xmm8, %xmm7
; SSE42-NEXT:    psubusb %xmm7, %xmm3
; SSE42-NEXT:    retq
;
; AVX2-LABEL: usubsat_v8i64_i8_narrow:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpbroadcastq {{.*#+}} ymm4 = [255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0]
; AVX2-NEXT:    vpand %ymm4, %ymm1, %ymm1
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    vpbroadcastq {{.*#+}} ymm4 = [18446744073709551360,18446744073709551360,18446744073709551360,18446744073709551360]
; AVX2-NEXT:    vpor %ymm4, %ymm2, %ymm2
; AVX2-NEXT:    vpsubusb %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm4, %ymm3, %ymm2
; AVX2-NEXT:    vpsubusb %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    retq
;
; AVX512-LABEL: usubsat_v8i64_i8_narrow:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpandq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %zmm0, %zmm0
; AVX512-NEXT:    vporq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %zmm1, %zmm1
; AVX512-NEXT:    vpsubusb %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %masked = and <8 x i64> %x, <i64 255, i64 255, i64 255, i64 255, i64 255, i64 255, i64 255, i64 255>
  %z = call <8 x i64> @llvm.usub.sat.v8i64(<8 x i64> %masked, <8 x i64> %y)
  ret <8 x i64> %z
}

; v4i64 narrowed to v32i8 - LHS masked to 8 bits, should use vpsubusb
define <4 x i64> @usubsat_v4i64_i8_narrow(<4 x i64> %x, <4 x i64> %y) nounwind {
; SSE2-LABEL: usubsat_v4i64_i8_narrow:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0]
; SSE2-NEXT:    pand %xmm4, %xmm1
; SSE2-NEXT:    pand %xmm4, %xmm0
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [18446744073709551360,18446744073709551360]
; SSE2-NEXT:    por %xmm4, %xmm2
; SSE2-NEXT:    psubusb %xmm2, %xmm0
; SSE2-NEXT:    por %xmm4, %xmm3
; SSE2-NEXT:    psubusb %xmm3, %xmm1
; SSE2-NEXT:    retq
;
; SSE42-LABEL: usubsat_v4i64_i8_narrow:
; SSE42:       # %bb.0:
; SSE42-NEXT:    movdqa {{.*#+}} xmm4 = [255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0]
; SSE42-NEXT:    pand %xmm4, %xmm1
; SSE42-NEXT:    pand %xmm4, %xmm0
; SSE42-NEXT:    movdqa {{.*#+}} xmm4 = [18446744073709551360,18446744073709551360]
; SSE42-NEXT:    por %xmm4, %xmm2
; SSE42-NEXT:    psubusb %xmm2, %xmm0
; SSE42-NEXT:    por %xmm4, %xmm3
; SSE42-NEXT:    psubusb %xmm3, %xmm1
; SSE42-NEXT:    retq
;
; AVX2-LABEL: usubsat_v4i64_i8_narrow:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm0, %ymm0
; AVX2-NEXT:    vpbroadcastq {{.*#+}} ymm2 = [18446744073709551360,18446744073709551360,18446744073709551360,18446744073709551360]
; AVX2-NEXT:    vpor %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpsubusb %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: usubsat_v4i64_i8_narrow:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpandq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm0, %ymm0
; AVX512-NEXT:    vporq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm1, %ymm1
; AVX512-NEXT:    vpsubusb %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %masked = and <4 x i64> %x, <i64 255, i64 255, i64 255, i64 255>
  %z = call <4 x i64> @llvm.usub.sat.v4i64(<4 x i64> %masked, <4 x i64> %y)
  ret <4 x i64> %z
}

; v8i32 narrowed to v32i8 - LHS masked to 8 bits, should use vpsubusb
define <8 x i32> @usubsat_v8i32_i8_narrow(<8 x i32> %x, <8 x i32> %y) nounwind {
; SSE2-LABEL: usubsat_v8i32_i8_narrow:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0]
; SSE2-NEXT:    pand %xmm4, %xmm1
; SSE2-NEXT:    pand %xmm4, %xmm0
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [4294967040,4294967040,4294967040,4294967040]
; SSE2-NEXT:    por %xmm4, %xmm2
; SSE2-NEXT:    psubusb %xmm2, %xmm0
; SSE2-NEXT:    por %xmm4, %xmm3
; SSE2-NEXT:    psubusb %xmm3, %xmm1
; SSE2-NEXT:    retq
;
; SSE42-LABEL: usubsat_v8i32_i8_narrow:
; SSE42:       # %bb.0:
; SSE42-NEXT:    movdqa {{.*#+}} xmm4 = [255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0]
; SSE42-NEXT:    pand %xmm4, %xmm1
; SSE42-NEXT:    pand %xmm4, %xmm0
; SSE42-NEXT:    movdqa {{.*#+}} xmm4 = [4294967040,4294967040,4294967040,4294967040]
; SSE42-NEXT:    por %xmm4, %xmm2
; SSE42-NEXT:    psubusb %xmm2, %xmm0
; SSE42-NEXT:    por %xmm4, %xmm3
; SSE42-NEXT:    psubusb %xmm3, %xmm1
; SSE42-NEXT:    retq
;
; AVX2-LABEL: usubsat_v8i32_i8_narrow:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm0, %ymm0
; AVX2-NEXT:    vpbroadcastd {{.*#+}} ymm2 = [4294967040,4294967040,4294967040,4294967040,4294967040,4294967040,4294967040,4294967040]
; AVX2-NEXT:    vpor %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpsubusb %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: usubsat_v8i32_i8_narrow:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpandd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm0, %ymm0
; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm1, %ymm1
; AVX512-NEXT:    vpsubusb %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %masked = and <8 x i32> %x, <i32 255, i32 255, i32 255, i32 255, i32 255, i32 255, i32 255, i32 255>
  %z = call <8 x i32> @llvm.usub.sat.v8i32(<8 x i32> %masked, <8 x i32> %y)
  ret <8 x i32> %z
}

; v8i32 narrowed to v16i16 - LHS masked to 16 bits, should use vpsubusw
define <8 x i32> @usubsat_v8i32_i16_narrow(<8 x i32> %x, <8 x i32> %y) nounwind {
; SSE2-LABEL: usubsat_v8i32_i16_narrow:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [65535,0,65535,0,65535,0,65535,0]
; SSE2-NEXT:    pand %xmm4, %xmm1
; SSE2-NEXT:    pand %xmm4, %xmm0
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [4294901760,4294901760,4294901760,4294901760]
; SSE2-NEXT:    por %xmm4, %xmm2
; SSE2-NEXT:    psubusw %xmm2, %xmm0
; SSE2-NEXT:    por %xmm4, %xmm3
; SSE2-NEXT:    psubusw %xmm3, %xmm1
; SSE2-NEXT:    retq
;
; SSE42-LABEL: usubsat_v8i32_i16_narrow:
; SSE42:       # %bb.0:
; SSE42-NEXT:    pxor %xmm4, %xmm4
; SSE42-NEXT:    pblendw {{.*#+}} xmm1 = xmm1[0],xmm4[1],xmm1[2],xmm4[3],xmm1[4],xmm4[5],xmm1[6],xmm4[7]
; SSE42-NEXT:    pblendw {{.*#+}} xmm0 = xmm0[0],xmm4[1],xmm0[2],xmm4[3],xmm0[4],xmm4[5],xmm0[6],xmm4[7]
; SSE42-NEXT:    movdqa {{.*#+}} xmm4 = [4294901760,4294901760,4294901760,4294901760]
; SSE42-NEXT:    por %xmm4, %xmm2
; SSE42-NEXT:    psubusw %xmm2, %xmm0
; SSE42-NEXT:    por %xmm4, %xmm3
; SSE42-NEXT:    psubusw %xmm3, %xmm1
; SSE42-NEXT:    retq
;
; AVX2-LABEL: usubsat_v8i32_i16_narrow:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vpblendw {{.*#+}} ymm0 = ymm0[0],ymm2[1],ymm0[2],ymm2[3],ymm0[4],ymm2[5],ymm0[6],ymm2[7],ymm0[8],ymm2[9],ymm0[10],ymm2[11],ymm0[12],ymm2[13],ymm0[14],ymm2[15]
; AVX2-NEXT:    vpbroadcastd {{.*#+}} ymm2 = [4294901760,4294901760,4294901760,4294901760,4294901760,4294901760,4294901760,4294901760]
; AVX2-NEXT:    vpor %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpsubusw %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: usubsat_v8i32_i16_narrow:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vpblendw {{.*#+}} ymm0 = ymm0[0],ymm2[1],ymm0[2],ymm2[3],ymm0[4],ymm2[5],ymm0[6],ymm2[7],ymm0[8],ymm2[9],ymm0[10],ymm2[11],ymm0[12],ymm2[13],ymm0[14],ymm2[15]
; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm1, %ymm1
; AVX512-NEXT:    vpsubusw %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %masked = and <8 x i32> %x, <i32 65535, i32 65535, i32 65535, i32 65535, i32 65535, i32 65535, i32 65535, i32 65535>
  %z = call <8 x i32> @llvm.usub.sat.v8i32(<8 x i32> %masked, <8 x i32> %y)
  ret <8 x i32> %z
}

; Negative test: LHS values may exceed 16 bits, should NOT narrow
define <8 x i32> @usubsat_v8i32_no_narrow(<8 x i32> %x, <8 x i32> %y) nounwind {
; SSE2-LABEL: usubsat_v8i32_no_narrow:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movdqa {{.*#+}} xmm4 = [2147483648,2147483648,2147483648,2147483648]
; SSE2-NEXT:    movdqa %xmm0, %xmm5
; SSE2-NEXT:    psubd %xmm2, %xmm0
; SSE2-NEXT:    pxor %xmm4, %xmm2
; SSE2-NEXT:    pxor %xmm4, %xmm5
; SSE2-NEXT:    pcmpgtd %xmm2, %xmm5
; SSE2-NEXT:    pand %xmm5, %xmm0
; SSE2-NEXT:    movdqa %xmm3, %xmm2
; SSE2-NEXT:    pxor %xmm4, %xmm2
; SSE2-NEXT:    pxor %xmm1, %xmm4
; SSE2-NEXT:    pcmpgtd %xmm2, %xmm4
; SSE2-NEXT:    psubd %xmm3, %xmm1
; SSE2-NEXT:    pand %xmm4, %xmm1
; SSE2-NEXT:    retq
;
; SSE42-LABEL: usubsat_v8i32_no_narrow:
; SSE42:       # %bb.0:
; SSE42-NEXT:    pmaxud %xmm2, %xmm0
; SSE42-NEXT:    psubd %xmm2, %xmm0
; SSE42-NEXT:    pmaxud %xmm3, %xmm1
; SSE42-NEXT:    psubd %xmm3, %xmm1
; SSE42-NEXT:    retq
;
; AVX2-LABEL: usubsat_v8i32_no_narrow:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpmaxud %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpsubd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: usubsat_v8i32_no_narrow:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpmaxud %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    vpsubd %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %z = call <8 x i32> @llvm.usub.sat.v8i32(<8 x i32> %x, <8 x i32> %y)
  ret <8 x i32> %z
}
