; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx10.2-512 < %s | FileCheck %s

; When 512-bit vectors are disabled by the preferred vector width, generic
; type legalization should split partial reductions to legal 256-bit halves.

define <16 x i32> @partial_reduce_sumla_i8_v16i32_prefer256(<16 x i32> %acc, <64 x i8> %a, <64 x i8> %b) #0 {
; CHECK-LABEL: partial_reduce_sumla_i8_v16i32_prefer256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpdpbusd %ymm2, %ymm4, %ymm0
; CHECK-NEXT:    vpdpbusd %ymm3, %ymm5, %ymm1
; CHECK-NEXT:    retq
  %a.sext = sext <64 x i8> %a to <64 x i32>
  %b.zext = zext <64 x i8> %b to <64 x i32>
  %mul = mul nsw <64 x i32> %a.sext, %b.zext
  %res = call <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v64i32(<16 x i32> %acc, <64 x i32> %mul)
  ret <16 x i32> %res
}

define <16 x i32> @partial_reduce_smla_i16_v16i32_prefer256(<16 x i32> %acc, <32 x i16> %a, <32 x i16> %b) #0 {
; CHECK-LABEL: partial_reduce_smla_i16_v16i32_prefer256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpdpwssd %ymm4, %ymm2, %ymm0
; CHECK-NEXT:    vpdpwssd %ymm5, %ymm3, %ymm1
; CHECK-NEXT:    retq
  %a.sext = sext <32 x i16> %a to <32 x i32>
  %b.sext = sext <32 x i16> %b to <32 x i32>
  %mul = mul nsw <32 x i32> %a.sext, %b.sext
  %res = call <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v32i32(<16 x i32> %acc, <32 x i32> %mul)
  ret <16 x i32> %res
}

define <16 x i32> @partial_reduce_smla_i8_v16i32_prefer256(<16 x i32> %acc, <64 x i8> %a, <64 x i8> %b) #0 {
; CHECK-LABEL: partial_reduce_smla_i8_v16i32_prefer256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpdpbssd %ymm4, %ymm2, %ymm0
; CHECK-NEXT:    vpdpbssd %ymm5, %ymm3, %ymm1
; CHECK-NEXT:    retq
  %a.sext = sext <64 x i8> %a to <64 x i32>
  %b.sext = sext <64 x i8> %b to <64 x i32>
  %mul = mul nsw <64 x i32> %a.sext, %b.sext
  %res = call <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v64i32(<16 x i32> %acc, <64 x i32> %mul)
  ret <16 x i32> %res
}

define <16 x i32> @partial_reduce_sumla_i16_v16i32_prefer256(<16 x i32> %acc, <32 x i16> %a, <32 x i16> %b) #0 {
; CHECK-LABEL: partial_reduce_sumla_i16_v16i32_prefer256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpdpwsud %ymm4, %ymm2, %ymm0
; CHECK-NEXT:    vpdpwsud %ymm5, %ymm3, %ymm1
; CHECK-NEXT:    retq
  %a.sext = sext <32 x i16> %a to <32 x i32>
  %b.zext = zext <32 x i16> %b to <32 x i32>
  %mul = mul nsw <32 x i32> %a.sext, %b.zext
  %res = call <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v32i32(<16 x i32> %acc, <32 x i32> %mul)
  ret <16 x i32> %res
}

define <16 x float> @partial_reduce_fmla_bf16_v16f32_prefer256(<16 x float> %acc, <32 x bfloat> %a, <32 x bfloat> %b) #0 {
; CHECK-LABEL: partial_reduce_fmla_bf16_v16f32_prefer256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vdpbf16ps %ymm4, %ymm2, %ymm0
; CHECK-NEXT:    vdpbf16ps %ymm5, %ymm3, %ymm1
; CHECK-NEXT:    retq
  %a.ext = fpext <32 x bfloat> %a to <32 x float>
  %b.ext = fpext <32 x bfloat> %b to <32 x float>
  %mul = fmul <32 x float> %a.ext, %b.ext
  %res = call <16 x float> @llvm.vector.partial.reduce.fadd.v16f32.v32f32(<16 x float> %acc, <32 x float> %mul)
  ret <16 x float> %res
}

declare <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v64i32(<16 x i32>, <64 x i32>)
declare <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v32i32(<16 x i32>, <32 x i32>)
declare <16 x float> @llvm.vector.partial.reduce.fadd.v16f32.v32f32(<16 x float>, <32 x float>)

attributes #0 = { "min-legal-vector-width"="256" "prefer-vector-width"="256" }
