; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512f,+avx512bw,+avx512vl,+avxvnniint16,-avx10.2 < %s | FileCheck %s

; Targets with AVX512 registers but only 256-bit AVX-VNNI-INT16 instructions
; should split 512-bit partial reductions to two 256-bit dot products instead
; of expanding them as zmm arithmetic.

define <16 x i32> @partial_reduce_sumla_i16_v16i32(<16 x i32> %acc, <32 x i16> %a, <32 x i16> %b) {
; CHECK-LABEL: partial_reduce_sumla_i16_v16i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vextractf64x4 $1, %zmm2, %ymm3
; CHECK-NEXT:    vextractf64x4 $1, %zmm1, %ymm4
; CHECK-NEXT:    vextractf64x4 $1, %zmm0, %ymm5
; CHECK-NEXT:    vpdpwsud %ymm3, %ymm4, %ymm5
; CHECK-NEXT:    vpdpwsud %ymm2, %ymm1, %ymm0
; CHECK-NEXT:    vinsertf64x4 $1, %ymm5, %zmm0, %zmm0
; CHECK-NEXT:    retq
  %a.sext = sext <32 x i16> %a to <32 x i32>
  %b.zext = zext <32 x i16> %b to <32 x i32>
  %mul = mul nsw <32 x i32> %a.sext, %b.zext
  %res = call <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v32i32(<16 x i32> %acc, <32 x i32> %mul)
  ret <16 x i32> %res
}

define <16 x i32> @partial_reduce_umla_i16_v16i32(<16 x i32> %acc, <32 x i16> %a, <32 x i16> %b) {
; CHECK-LABEL: partial_reduce_umla_i16_v16i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vextractf64x4 $1, %zmm2, %ymm3
; CHECK-NEXT:    vextractf64x4 $1, %zmm1, %ymm4
; CHECK-NEXT:    vextractf64x4 $1, %zmm0, %ymm5
; CHECK-NEXT:    vpdpwuud %ymm3, %ymm4, %ymm5
; CHECK-NEXT:    vpdpwuud %ymm2, %ymm1, %ymm0
; CHECK-NEXT:    vinsertf64x4 $1, %ymm5, %zmm0, %zmm0
; CHECK-NEXT:    retq
  %a.zext = zext <32 x i16> %a to <32 x i32>
  %b.zext = zext <32 x i16> %b to <32 x i32>
  %mul = mul <32 x i32> %a.zext, %b.zext
  %res = call <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v32i32(<16 x i32> %acc, <32 x i32> %mul)
  ret <16 x i32> %res
}

declare <16 x i32> @llvm.vector.partial.reduce.add.v16i32.v32i32(<16 x i32>, <32 x i32>)
