; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --filter "active.lane.mask" --version 6
; RUN: opt -mtriple=aarch64 -mcpu=neoverse-v1 -passes=loop-vectorize -force-vector-width="vscale x 4" -force-vector-interleave=1 -tail-folding-policy=prefer-fold-tail -disable-output -vplan-print-after=printOptimizedVPlan %s 2>&1 | FileCheck %s

; We never emit a scalable active.lane.mask that can be folded to a constant.
define i32 @scalable_alm_liveins(ptr %A, ptr noalias %B) {
; CHECK-LABEL: VPlan for loop in 'scalable_alm_liveins'
; CHECK:    EMIT vp<%active.lane.mask.entry> = active lane mask vp<%index.part.next>, ir<1002>, ir<1>
; CHECK:      ACTIVE-LANE-MASK-PHI vp<[[VP5:%[0-9]+]]> = phi vp<%active.lane.mask.entry>, vp<%active.lane.mask.next>
; CHECK:      EMIT vp<%active.lane.mask.next> = active lane mask vp<[[VP8:%[0-9]+]]>, ir<1002>, ir<1>
; CHECK:      EMIT vp<[[VP9:%[0-9]+]]> = not vp<%active.lane.mask.next>
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %for = phi i16 [ 0, %entry ], [ %for.next, %loop ]
  %sext = sext i16 %for to i32
  %iv.next = add i64 %iv, 1
  %gep.A = getelementptr i32, ptr %A, i64 %iv.next
  %for.next = load i16, ptr %gep.A, align 2
  %gep.B = getelementptr i32, ptr %B, i64 %iv.next
  store i32 %sext, ptr %gep.B
  %ec = icmp eq i64 %iv, 1001
  br i1 %ec, label %exit, label %loop

exit:
  ret i32 0
}
